// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using manders_api.Services;

namespace manders_api.Migrations
{
    [DbContext(typeof(DbService))]
    [Migration("20200629130119_schedule-added")]
    partial class scheduleadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("manders_api.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Double")
                        .HasColumnType("bit");

                    b.Property<bool>("Handled")
                        .HasColumnType("bit");

                    b.Property<bool>("Reminded")
                        .HasColumnType("bit");

                    b.Property<int?>("SlotId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("manders_api.Models.PageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("manders_api.Models.PageImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("manders_api.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("manders_api.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId1")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId2")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId3")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId4")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId5")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId6")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ScheduleId1");

                    b.HasIndex("ScheduleId2");

                    b.HasIndex("ScheduleId3");

                    b.HasIndex("ScheduleId4");

                    b.HasIndex("ScheduleId5");

                    b.HasIndex("ScheduleId6");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("manders_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("manders_api.Models.Appointment", b =>
                {
                    b.HasOne("manders_api.Models.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId");

                    b.HasOne("manders_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("manders_api.Models.Slot", b =>
                {
                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Friday")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Monday")
                        .HasForeignKey("ScheduleId1");

                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Saturday")
                        .HasForeignKey("ScheduleId2");

                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Sunday")
                        .HasForeignKey("ScheduleId3");

                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Thursday")
                        .HasForeignKey("ScheduleId4");

                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Tuesday")
                        .HasForeignKey("ScheduleId5");

                    b.HasOne("manders_api.Models.Schedule", null)
                        .WithMany("Wednesday")
                        .HasForeignKey("ScheduleId6");
                });
#pragma warning restore 612, 618
        }
    }
}
